<?php

namespace App\Http\Controllers;

use App\Models\Peserta;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

class RegistrationController extends Controller
{
    /**
     * Store a new registration
     */
    public function store(Request $request)
    {
        // Validate input
        $validator = Validator::make($request->all(), [
            'nama_lengkap' => 'required|string|min:3|max:255',
            'email' => 'required|email|unique:peserta,email|max:255',
            'no_hp' => ['required', 'string', 'regex:/^(\+62|62|0)[0-9]{9,12}$/', 'max:20'],
            'asal_instansi' => 'required|string|min:3|max:255',
        ], [
            'nama_lengkap.required' => 'Nama lengkap wajib diisi',
            'nama_lengkap.min' => 'Nama lengkap minimal 3 karakter',
            'email.required' => 'Email wajib diisi',
            'email.email' => 'Format email tidak valid',
            'email.unique' => 'Email sudah terdaftar',
            'no_hp.required' => 'Nomor HP wajib diisi',
            'no_hp.regex' => 'Format nomor HP tidak valid (contoh: 081234567890)',
            'asal_instansi.required' => 'Asal instansi wajib diisi',
            'asal_instansi.min' => 'Asal instansi minimal 3 karakter',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'message' => 'Validasi gagal',
                'errors' => $validator->errors(),
            ], 422);
        }

        try {
            // Normalize phone number
            $normalizedPhone = $this->normalizePhoneNumber($request->no_hp);

            // Create new peserta (id_peserta, qr_code_token, tgl_registrasi auto-generated by model)
            $peserta = Peserta::create([
                'nama_lengkap' => $request->nama_lengkap,
                'email' => $request->email,
                'no_hp' => $normalizedPhone,
                'asal_instansi' => $request->asal_instansi,
            ]);

            // Optional: Generate and save QR Code image
            // $this->generateAndSaveQRCode($peserta);

            // Optional: Send confirmation email
            // $this->sendConfirmationEmail($peserta);

            return response()->json([
                'success' => true,
                'message' => 'Pendaftaran berhasil!',
                'id_peserta' => $peserta->id_peserta,
                'data' => [
                    'nama_lengkap' => $peserta->nama_lengkap,
                    'email' => $peserta->email,
                    'no_hp' => $peserta->no_hp,
                    'asal_instansi' => $peserta->asal_instansi,
                    'tgl_registrasi' => $peserta->tgl_registrasi->format('d F Y H:i'),
                ],
                'instructions' => [
                    'check_in_url' => route('check-in.form'),
                    'message' => 'Simpan ID Peserta Anda: '.$peserta->id_peserta,
                    'note' => 'Di hari H, buka halaman Check-in dan masukkan ID Anda untuk mendapatkan QR Code absensi.',
                ],
            ], 201);

        } catch (\Exception $e) {
            \Log::error('Registration error: '.$e->getMessage());

            return response()->json([
                'success' => false,
                'message' => 'Terjadi kesalahan saat pendaftaran. Silakan coba lagi.',
                'error' => config('app.debug') ? $e->getMessage() : null,
            ], 500);
        }
    }

    /**
     * Show success page (optional - if you want dedicated success page)
     */
    public function success($id_peserta)
    {
        try {
            $peserta = Peserta::where('id_peserta', strtoupper($id_peserta))->firstOrFail();

            return view('success', compact('peserta'));
        } catch (\Exception $e) {
            return redirect()->route('home')
                ->with('error', 'ID Peserta tidak ditemukan');
        }
    }

    /**
     * Download QR Code as PNG
     */
    public function downloadQr($id_peserta)
    {
        try {
            $peserta = Peserta::where('id_peserta', strtoupper($id_peserta))->firstOrFail();

            // Generate QR Code
            $qrCode = QrCode::format('png')
                ->size(400)
                ->margin(2)
                ->errorCorrection('H')
                ->generate($peserta->qr_code_token);

            return response($qrCode)
                ->header('Content-Type', 'image/png')
                ->header('Content-Disposition', 'attachment; filename="QR-AlAzharExpo-'.$peserta->id_peserta.'.png"');

        } catch (\Exception $e) {
            return redirect()->route('home')
                ->with('error', 'QR Code tidak dapat diunduh');
        }
    }

    /**
     * Show check-in form (untuk pengunjung)
     */
    public function checkInForm()
    {
        return view('check-in.form');
    }

    /**
     * Verify ID and show QR Code
     */
    public function verifyId(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'id_peserta' => 'required|string|size:4',
        ], [
            'id_peserta.required' => 'ID Peserta wajib diisi',
            'id_peserta.size' => 'ID Peserta harus 4 karakter',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'message' => $validator->errors()->first(),
            ], 422);
        }

        // Cari peserta berdasarkan ID (case insensitive)
        $peserta = Peserta::where('id_peserta', strtoupper($request->id_peserta))->first();

        if (! $peserta) {
            return response()->json([
                'success' => false,
                'message' => 'ID Peserta tidak ditemukan. Pastikan ID sudah benar.',
            ], 404);
        }

        // Generate QR Code SVG untuk ditampilkan
        $qrCodeSvg = QrCode::format('svg')
            ->size(300)
            ->margin(1)
            ->errorCorrection('H')
            ->generate($peserta->qr_code_token);

        return response()->json([
            'success' => true,
            'message' => 'ID Valid! Silakan scan QR Code di bawah ini pada saat check-in.',
            'data' => [
                'id_peserta' => $peserta->id_peserta,
                'nama_lengkap' => $peserta->nama_lengkap,
                'asal_instansi' => $peserta->asal_instansi,
                'email' => $peserta->email,
                'qr_code_token' => $peserta->qr_code_token,
                'qr_code_svg' => base64_encode($qrCodeSvg),
                'tgl_registrasi' => $peserta->tgl_registrasi->format('d F Y H:i'),
                'download_url' => route('qr.download', $peserta->id_peserta),
            ],
        ], 200);
    }

    /**
     * Check if email already registered
     */
    public function checkEmail(Request $request)
    {
        $exists = Peserta::where('email', $request->email)->exists();

        return response()->json([
            'available' => ! $exists,
            'message' => $exists ? 'Email sudah terdaftar' : 'Email tersedia',
        ]);
    }

    /**
     * Normalize phone number to standard format
     */
    private function normalizePhoneNumber($phone)
    {
        // Remove spaces, dashes, etc
        $phone = preg_replace('/[^0-9+]/', '', $phone);

        // Convert +62 or 62 to 0
        if (substr($phone, 0, 3) === '+62') {
            $phone = '0'.substr($phone, 3);
        } elseif (substr($phone, 0, 2) === '62') {
            $phone = '0'.substr($phone, 2);
        }

        return $phone;
    }

    /**
     * Generate and save QR Code to storage (optional)
     */
    private function generateAndSaveQRCode($peserta)
    {
        try {
            $qrCode = QrCode::format('png')
                ->size(400)
                ->margin(2)
                ->errorCorrection('H')
                ->generate($peserta->qr_code_token);

            // Save to storage
            $path = 'qrcodes/'.$peserta->id_peserta.'.png';
            Storage::put('public/'.$path, $qrCode);

            // Update peserta with QR path (if you have qr_path column)
            // $peserta->update(['qr_code_path' => $path]);

            return $path;
        } catch (\Exception $e) {
            \Log::error('QR Code generation error: '.$e->getMessage());

            return null;
        }
    }

    /**
     * Send confirmation email (implement this later)
     */
    private function sendConfirmationEmail($peserta)
    {
        // TODO: Implement email sending
        // Example:
        // try {
        //     Mail::to($peserta->email)->send(new RegistrationConfirmation($peserta));
        // } catch (\Exception $e) {
        //     \Log::error('Email sending error: ' . $e->getMessage());
        // }
    }
}
